### ISSUE TITLE
Not failing as expected

### ISSUE THREAD

**Issue by truthdoug** [cchantep/probot-pr-status-label#68]
I'm stumped. I'm applying a label to a PR that should cause it to fail but it doesn't.

My `pr-status-label.json` is a copy of the default:

```javascript
{
  "requiredStatusRegex": "^:[^:]+: ([^:]+):required$",
  "pendingStatusRegex": "^:[^:]+: ([^:]+):pending$",
  "successStatusRegex": "^:[^:]+: ([^:]+):(?:ok|success)$",
  "errorStatusRegex": "^:[^:]+: ([^:]+):(ko|error)$"
}

```

My `pr-status-label.yml`:
```yml
name: PR status label

on:
  pull_request:
    types: ['labeled', 'synchronize']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: cchantep/probot-pr-status-label@ghaction-1.0.x
```

Here's the full list of labels on my repo:

```
':bust_in_silhouette: UAT:pending',
 ':bust_in_silhouette: UAT:required',
 ':closed_lock_with_key: security-review:required',
 ':eyes: UAT-passed:ok',
 ':lock: security-review:ok',
 ':open_mouth: security-review:pending',
 ':see_no_evil: UAT-not-needed:ok',
 ':warning: security-review:error',
 'bug',
 'dependencies',
 'enhancement',
 'help wanted',
 'invalid',
 'wontfix'
```

*Action:* I apply `:warning: security-review:error` to the PR (with no other labels set) and the test runs and succeeds. I expect it to fail the check.

![pr-status-label-output](https://user-images.githubusercontent.com/20690067/92158108-6aa41800-edf9-11ea-83a3-05b3fd86eccd.png)
![github-checks](https://user-images.githubusercontent.com/20690067/92158228-91624e80-edf9-11ea-8f0f-15a67475a42c.png)

Things I've considered and explored:
* I've checked the regexp and label that the error label matches the pattern in the errorStatusRegex (and doesn't match any of the other patterns).
* I  set repo secrets `ACTIONS_STEP_DEBUG` and `ACTIONS_RUNNER_DEBUG` both to `true` for extra debugging info - nothing interesting in logs.
* I added `uses: actions/checkout@v2` to the yml file so that it would check out the repo on the proper branch (even though my config json file is the same as the default)

What's going on here?
